version: "3.8"
services:
  db:
    image: postgres
    container_name: pgdb
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: webprogramming
      POSTGRES_DB: FRIS-DB
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ariannejacosta@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwertyuiop
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: webprogramming
      DATABASE_NAME: FRIS-DB
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  backend:
    image: backend
    build:
      context: ./backend-fixed
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/FRIS-DB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: webprogramming
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - backend

  nginx:
    image: nginx
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  local_pgdata:
  pgadmin-data:
